In [3]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]


In [4]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers * 2)

[20 40 60 80]


In [5]:
numbers = [10, 20, 30, 40]

print(numbers * 2)

[10, 20, 30, 40, 10, 20, 30, 40]


In [6]:
arr = np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
import numpy as np
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#np.full()
arr = np.full(6,7)

print(arr)

[7 7 7 7 7 7]


In [18]:
#np.arange
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [19]:
arr = np.arange(0,10,2) #to arrange even numbers in range

print(arr)

[0 2 4 6 8]


In [26]:
#np.linspace
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [21]:
#creating an array using random numbers
#np.random
arr = np.random.rand(5)

print(arr)

[0.3233567  0.98062175 0.43040848 0.22397704 0.11881188]


In [25]:
arr = np.random.rand(1, 100, 5)

print(arr)

[[[0.05022498 0.94241065 0.30090945 0.83022369 0.02993917]
  [0.48137543 0.69173374 0.92732704 0.97893441 0.42624588]
  [0.26569321 0.77304082 0.30803109 0.56268881 0.05330315]
  [0.03738955 0.8393689  0.04189302 0.29828421 0.67238488]
  [0.70150523 0.32077801 0.71095928 0.0634143  0.52761365]
  [0.27374205 0.01304692 0.52325965 0.1578966  0.69216303]
  [0.10420371 0.67057646 0.07572027 0.63222827 0.61267698]
  [0.58738639 0.1486193  0.72107525 0.24751347 0.40611419]
  [0.92550896 0.23544548 0.84485416 0.67627333 0.70589644]
  [0.35885591 0.34062651 0.6225739  0.98971296 0.89091111]
  [0.24870419 0.98900104 0.81561757 0.6113993  0.09252696]
  [0.55446541 0.77407085 0.37026361 0.07987512 0.29167177]
  [0.23725688 0.77247714 0.06776948 0.31313444 0.06463526]
  [0.56942047 0.59892489 0.65251707 0.66863146 0.1300983 ]
  [0.14296704 0.33740946 0.90942279 0.52241822 0.29371659]
  [0.30389485 0.2696493  0.90823486 0.8728635  0.41319499]
  [0.75199621 0.44079    0.74148266 0.09911604 0.9747094

In [30]:
# Random 2D Array
arr = np.random.randint(1, 10, size = (3,4))

print(arr)

[[6 4 7 2]
 [6 5 5 8]
 [8 9 8 6]]


In [32]:
arr = np.array((10, 50, 20, 80, 30))

print(arr.max())
print(arr.min())

80
10
