In [1]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]


In [2]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers * 2)

[20 40 60 80]


In [3]:
numbers = [10, 20, 30, 40]

print(numbers * 2)

[10, 20, 30, 40, 10, 20, 30, 40]


In [4]:
arr = np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#np.full()
arr = np.full(6,7)

print(arr)

[7 7 7 7 7 7]


In [7]:
#np.arange
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(0,10,2) #to arrange even numbers in range

print(arr)

[0 2 4 6 8]


In [9]:
#np.linspace
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
#creating an array using random numbers
#np.random
arr = np.random.rand(5)

print(arr)

[0.19751922 0.60088756 0.57433929 0.47533834 0.29590393]


In [11]:
arr = np.random.rand(1, 100, 5)

print(arr)

[[[8.05393466e-02 9.14765015e-01 3.58838363e-04 7.34765625e-01
   6.69558350e-01]
  [2.89582056e-01 1.05514999e-01 2.79463087e-01 1.15517297e-01
   6.38223496e-01]
  [7.00938378e-01 2.88806747e-01 7.32902026e-01 5.60988585e-01
   5.32649116e-02]
  [9.64732072e-01 5.79250332e-01 5.68668917e-01 9.60176052e-01
   5.79522899e-01]
  [5.32321952e-01 5.63643127e-01 6.96190039e-01 2.06154226e-01
   7.91844259e-01]
  [4.39947851e-01 7.28579931e-01 1.98083089e-01 4.36288109e-01
   7.22955286e-01]
  [4.19329287e-01 1.79307276e-01 3.41136822e-01 1.88731000e-01
   4.81545940e-01]
  [1.79127733e-01 5.90086338e-01 1.06153943e-03 4.22299139e-01
   9.29630540e-01]
  [8.45613527e-01 2.23971026e-01 4.57308679e-02 3.68073259e-01
   1.91829777e-01]
  [2.91603176e-01 3.82068189e-01 6.02643683e-01 9.73195174e-01
   7.74902130e-01]
  [5.88658661e-02 7.89248140e-01 5.84413170e-01 9.88154714e-01
   1.62150300e-01]
  [9.55884297e-01 3.14108564e-01 7.92189326e-01 5.80625930e-01
   3.45507071e-01]
  [5.06757127e-0

In [12]:
# Random 2D Array
arr = np.random.randint(1, 10, size = (3,4))

print(arr)

[[2 4 5 6]
 [5 9 8 1]
 [9 7 5 2]]


In [13]:
arr = np.array((10, 50, 20, 80, 30))

print(arr.max())
print(arr.min())

80
10


In [14]:
import pandas as pd
ages = pd.Series([20, 25, 30,  35])

print(ages)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd

ages = pd.Series(
    [10, 20, 30],
    index=["Ali", "Ahmad", "Sara"]
)

print(ages)

In [ ]:
data = {
    "Name": ["Ali", "Ahmad", "Sara"],
    "Age": [24, 30, 28],
    "Salary": [50000, 70000, 60000]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
df[(df["Age"] > 25) & (df["Salary"] > 60000)]

In [ ]:
df[(df["Age"] < 26) | (df["Salary"] > 80000)]

In [ ]:
df = pd.DataFrame(data)

df.set_index("Name", inplace=True)
print(df)

In [25]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmad", "Sara"],
    "Age": [24, 30, 28],
    "Salary": [50000, 70000, 60000]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

df.set_index("Name", inplace=True)

print("\nAfter:")
print(df)

Before:
    Name  Age  Salary
0    Ali   24   50000
1  Ahmad   30   70000
2   Sara   28   60000

After:
       Age  Salary
Name              
Ali     24   50000
Ahmad   30   70000
Sara    28   60000


# Pandas

In [ ]:
import pandas as pd

students = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 4, 5],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "age": [20, 22, 21, 23, 25]
    }
)

scores = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 6],
        "marks": [85, 90, 78, 88]
    }
)

print("Students:")
print(students)
print("\nScores:")
print(scores)

Students:
   student_id    name department  age
0           1     Ali         CS   20
1           2    Sara         IT   22
2           3   Ahmed         CS   21
3           4  Ayesha         IT   23
4           5   Usman         CS   25

Scores:
   student_id  marks
0           1     85
1           2     90
2           3     78
3           6     88


In [ ]:
pd.merge(
    students,
    scores,
    on= "student_id",
    how = "inner"
)

,student_id,name,department,age,marks
0,1,Ali,CS,20,85
1,2,Sara,IT,22,90
2,3,Ahmed,CS,21,78


In [26]:
import pandas as pd

students = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 4, 5],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "age": [20, 22, 21, 23, 25]
    }
)

scores = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 6],
        "marks": [85, 90, 78, 88]
    }
)

# Corrected merge
right_joined_df = pd.merge(students, scores, on="student_id", how="right")
print(right_joined_df)

   student_id   name department   age  marks
0           1    Ali         CS  20.0     85
1           2   Sara         IT  22.0     90
2           3  Ahmed         CS  21.0     78
3           6    NaN        NaN   NaN     88


In [27]:
pd.merge(
    students,
    scores,
    on= "student_id",
    how = "left"
)

,student_id,name,department,age,marks
0,1,Ali,CS,20,85.0
1,2,Sara,IT,22,90.0
2,3,Ahmed,CS,21,78.0
3,4,Ayesha,IT,23,NaN
4,5,Usman,CS,25,NaN


In [30]:
students_indeexed = students.set_index("student_id")
scores_indexed = scores.set_index("student_id")

result = students_indeexed.join(scores_indexed, how="left")
print(result)

              name department  age  marks
student_id                               
1              Ali         CS   20   85.0
2             Sara         IT   22   90.0
3            Ahmed         CS   21   78.0
4           Ayesha         IT   23    NaN
5            Usman         CS   25    NaN


In [37]:
df1 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "marks": [85, 90]
    }
)

df2 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "age": [20, 22]
    }
)

result = pd.concat([df1, df2], axis=1)
print(result)

   name  marks  name  age
0   Ali     85   Ali   20
1  Sara     90  Sara   22


In [ ]:
left = pd.DataFrame({
    "name": ["Ali", "Sara"]
})
right = pd.DataFrame({
    "marks": [85, 90]
})

result = pd.concat([left, right], axis=1)
print(result)

   name  marks
0   Ali     85
1  Sara     90


In [38]:
df1 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "marks": [85, 90]
    }
)

df2 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "age": [20, 22]
    }
)

result = pd.concat([df1, df2], axis=0, ignore_index=True)
print(result)

   name  marks   age
0   Ali   85.0   NaN
1  Sara   90.0   NaN
2   Ali    NaN  20.0
3  Sara    NaN  22.0


In [40]:
df = pd.DataFrame(
    {
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "marks": [85, 90, 78, 88, 92],
        "ages": [20, 22, 21, 23, 25]
    }
)

df.groupby("department")["marks"].mean()

department
CS    85.0
IT    89.0
Name: marks, dtype: float64

In [41]:
df.groupby("department")["marks"].agg(
    ["mean", "max", "min", "count"]
)

,mean,max,min,count
department,,,,
CS,85.0,92,78,3
IT,89.0,90,88,2


In [45]:
df = pd.DataFrame(
    {
        "name": ["Ali", "Sara", "Sara", "Ahmed"],
        "age": [18, 25, 42, 65]
    }
)

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 20, 40, 60, 100],
    labels=["Young", "Adult","Middle-aged", "Senior"]
)